def blosum62(a: bytes, b: bytes) -> int: ...
def pam120(a: bytes, b: bytes) -> int: ...
def pam200(a: bytes, b: bytes) -> int: ...
def pam250(a: bytes, b: bytes) -> int: ...
def pam40(a: bytes, b: bytes) -> int: ...
