from typing import Optional


def hamming(alpha: bytes, beta: bytes) -> int: ...
def simd_hamming(alpha: bytes, beta: bytes) -> int: ...
def levenshtein(alpha: bytes, beta: bytes) -> int: ...
def simd_levenshtein(alpha: bytes, beta: bytes) -> int: ...
def simd_bounded_levenshtein(alpha: bytes, beta: bytes, k: int) -> Optional[int]: ...
