from typing import Sequence


class Orf:
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def offset(self) -> int: ...
    def __repr__(self) -> str: ...


class Finder:
    def __new__(cls, start: Sequence[bytes], stop: Sequence[bytes], min_len: int) -> Finder: ...
    def find_all(self, sequence: bytes) -> Sequence[Orf]: ...
