from . import Alphabet


def make_rna_alphabet() -> Alphabet: ...
def make_rna_n_alphabet() -> Alphabet: ...
def make_rna_iupac_alphabet() -> Alphabet: ...
def get_rna_symbol_complement(chr: bytes) -> bytes: ...
def get_rna_complement(text: bytes) -> bytes: ...
