name: CI

on: [push]

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          name: Clippy Output

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  linux-build:
    name: Build for Linux
    runs-on: ubuntu-latest
    needs: [clippy, fmt]
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64, x86]
        manylinux: [auto]
        include:
          - target: aarch64
            container: messense/manylinux_2_24-cross:aarch64
          - target: armv7
            container: messense/manylinux_2_24-cross:armv7
          - target: s390x
            container: messense/manylinux_2_24-cross:ppc64le
          - target: ppc64le
            container: messense/manylinux_2_24-cross:s390x
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --interpreter 3.7 3.8 3.9 3.10 3.11
          manylinux: ${{ matrix.manylinux }}
          rust-toolchain: stable

      - run: ls -lh dist/

      - name: install & test
        if: ${{ startsWith(matrix.target, 'x86') }}
        shell: bash
        run: |
          rm -r bioforma
          pip install pytest
          pip install bioforma --no-index --no-deps --find-links dist --force-reinstall
          pytest

      - name: install & test
        if: ${{ !startsWith(matrix.target, 'x86') }}
        uses: uraimo/run-on-arch-action@v2.5.0
        with:
          arch: ${{ matrix.target }}
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          install: |
            rm -r bioforma
            apt-get update
            apt-get install -y --no-install-recommends python3 python3-pip
            python3 -m pip install -U pip pytest
            python3 -m pip install bioforma --no-index --no-deps --find-links dist --force-reinstall
            pytest

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist
